name: Latest Medium Articles
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
    contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "20"
          feed_list: "https://medium.com/feed/tag/micro-frontends, https://medium.com/feed/tag/module-federation"
          template: "<tr><td><a target='_blank' href=$url>$title</a></td><td><code>$categories</code></td></tr>"